### ISSUE TITLE
libvpx will not install on G4 10.4

### ISSUE THREAD

**Issue by roadtechy** [mistydemeo/tigerbrew#322]
Hello,

I am having an issue installing the libvpx formula.  I've tried the brew sh option as well.  Any help is greatly appreciated.

Thanks,
Cevin 

Detailed information follows:

System Info:
----------
brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 752436e19a81f824712662ab39a50a6a1adab5a4
Last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 32-bit g4
OS X: 10.4.11-Power Macintosh
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
Clang: N/A
X11: N/A
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.3/bin/python
Ruby: /usr/bin/ruby
Java: N/A

----------
brew doctor
Your system is ready to brew.

----------
brew --env
CC: gcc-4.2
CXX: g++-4.2
OBJC: gcc-4.2
OBJCXX: g++-4.2
CFLAGS: -Os -w -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4
CXXFLAGS: -Os -w -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4
LDFLAGS: -L/usr/local/lib -Wl,-headerpad_max_install_names
MAKEFLAGS: -j1
MACOSX_DEPLOYMENT_TARGET: 10.4
PKG_CONFIG_LIBDIR: /usr/local/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.4:/usr/lib/pkgconfig
PATH: /usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/Library/ENV/scm:/usr/local/Library/ENV/scm
CPATH: /usr/local/include

##------##

Errors:

----------
Download & Install of libvpx:

brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
######################################################################## 100.0%
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-
==> make install

make install

../libs.mk:273: *** missing `endif'.  Stop.
make: *** [.DEFAULT] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

----------
Second attempt to install libvpx:

brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-
==> make install

make install

../libs.mk:273: *** missing `endif'.  Stop.
make: *** [.DEFAULT] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

----------

brew sh
Your shell has been configured to use Tigerbrew's build environment:
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit'.

brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> Verifying libvpx-1.4.0.tar.gz checksum
/usr/bin/tar xzf /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-unit-tests --disable-examples
  enabling pic
  disabling unit_tests
  disabling examples
Configuring selected codecs
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'generic-gnu'
  enabling generic
  enabling webm_io
  enabling libyuv
Creating makefiles for generic-gnu libs
Creating makefiles for generic-gnu docs
==> make install
../libs.mk:273: *** missing `endif'.  Stop.
make: *** [.DEFAULT] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

----------

**Comment by roadtechy** [comment]
Found this in my journies:

"#   - `make` on 10.4 fails on recent libvpx Makefiles due to a bug with define/enddef processing.
#     This can be worked around by building a current version of make from sources."

http://www.telegraphics.com.au/svn/webpformat/trunk/Makefile

Thanks,
Cevin

**Comment by mistydemeo** [comment]
Thank you! Fixed by marking a dependency on a newer version of make on Tiger.

**Comment by roadtechy** [comment]
Hello,

Thanks!  With the new install of make I still have issues.  I deleted the tar from the cache folder, rebooted and gave it a whirl again.  Still kicking the same error.  Do I need to tell tigerbrew to use the new make that is in the keg via the flags shown below?  If so, how?

I saw this quote so I was wondering:
"We allow a certain degree of configurability using Homebrew's options and environment variables, but allowing users to specify arbitrary CFLAGS is a support nightmare. There are a lot of ways that that could go badly"

Thanks!
 
----------
brew install homebrew/dupes/make
==> Tapping Homebrew/dupes
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 1665, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1665 (delta 0), reused 0 (delta 0), pack-reused 1662
Receiving objects: 100% (1665/1665), 339.87 KiB | 375.00 KiB/s, done.
Resolving deltas: 100% (919/919), done.
Checking connectivity... done.
Warning: Could not create link for homebrew/dupes/apple-gcc42, as it
conflicts with mistydemeo/tigerbrew/apple-gcc42. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/dupes/apple-gcc42
Tapped 39 formulae (62 files, 636K)
==> Installing make from homebrew/homebrew-dupes
==> Downloading http://ftpmirror.gnu.org/make/make-4.1.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/make/4.1
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    CPPFLAGS: -I/usr/local/opt/make/include

==> Summary
/usr/local/Cellar/make/4.1: 11 files, 920K, built in 2.2 minutes

----------
brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> Verifying libvpx-1.4.0.tar.gz checksum
/usr/bin/tar xzf /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-unit-tests --disable-examples
  enabling pic
  disabling unit_tests
  disabling examples
Configuring selected codecs
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'generic-gnu'
  enabling generic
  enabling webm_io
  enabling libyuv
Creating makefiles for generic-gnu libs
Creating makefiles for generic-gnu docs
==> make install
../libs.mk:273: *** missing `endif'.  Stop.
make: *** [.DEFAULT] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

----------

**Comment by mistydemeo** [comment]
Hm, have you run `brew update` yet?

**Comment by mistydemeo** [comment]
Can I see your `brew --config` and `brew doctor`, please?

**Comment by roadtechy** [comment]
Doh

**Comment by roadtechy** [comment]
Danke!

brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-
==> make install
/usr/local/Cellar/libvpx/1.4.0: 16 files, 1.6M, built in 8.5 minutes
casis:~ casisii$ /usr/local/Cellar/libvpx/1.4.0: 16 files, 1.6M, built in 8.5 minutes

**Comment by mistydemeo** [comment]
Excellent! Glad it works! :sparkles:
