### ISSUE TITLE
doxygen failed to install (10.5/G5)

### ISSUE THREAD

**Issue by ghost** [mistydemeo/tigerbrew#371]
https://gist.github.com/87907820afa034d9e59f

**Comment by mistydemeo** [comment]
```
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Failed
-- Could NOT find ICONV (missing:  ICONV_COMPILES) 
CMake Error at cmake/FindIconv.cmake:121 (MESSAGE):
  Unable to determine iconv() signature
Call Stack (most recent call first):
  CMakeLists.txt:64 (find_package)
```

Do you mind redoing the build with `-d` and fetching a copy of the logs referenced here?

```
-- Configuring incomplete, errors occurred!
See also "/tmp/doxygen20151226-67158-9y7ikq/doxygen-1.8.10/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/doxygen20151226-67158-9y7ikq/doxygen-1.8.10/build/CMakeFiles/CMakeError.log".
```

**Comment by mistydemeo** [comment]
Should be fixed now!

**Comment by w-hive** [comment]
Still not working :(

https://gist.github.com/93ff02e7af7717bd5eae

**Comment by betojsp** [comment]
Not working :S

**Comment by mistydemeo** [comment]
Can you do `brew install doxygen -d`, and give me the logs from `CMakeFiles`? I'll need those to diagnose. Thanks!

**Comment by mistydemeo** [comment]
OK, should be fixed (for real this time).

**Comment by betojsp** [comment]
Perfect @mistydemeo 
MDC:~ mdc$ brew install doxygen
==> Downloading http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/doxygen-1.8.10.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/doxygen/1.8.10 -DCMAKE_BUILD_TYPE=Rele
==> make


/usr/local/Cellar/doxygen/1.8.10: 8 files, 13M, built in 23.0 minutes

**Comment by GoChanGo** [comment]
What was the fix? I'm running into the same problem trying to compile doxygen.

**Comment by mistydemeo** [comment]
@gochango Mind opening a new issue with debugging info? The fix I merged in this case should still be in effect, so you might have a new problem.

**Comment by jrgleason** [comment]
Same problem here

```
CMake Error at cmake/FindIconv.cmake:130 (MESSAGE):
  Unable to determine iconv() signature
```

**Comment by edt11x** [comment]
Same type of problem on 1.8.14:

-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Failed
-- Could NOT find ICONV (missing:  ICONV_COMPILES) 
CMake Error at cmake/FindIconv.cmake:130 (MESSAGE):
  Unable to determine iconv() signature
Call Stack (most recent call first):
  CMakeLists.txt:92 (find_package)

**Comment by mistydemeo** [comment]
Can repro. Looks like it's trying to pass a flag that GCC 4.2 doesn't support:

> cc1plus: error: unrecognized command line option "-Wno-deprecated-register"

**Comment by mistydemeo** [comment]
Should be fixed on Tiger now.

**Comment by stayprivates** [comment]
Same problem trying to build 1.8.14 on Ubuntu 18.04, with cmake 3.10.2

-- Performing Test ICONV_COMPILES - Failed
-- Could NOT find ICONV (missing: ICONV_TEST ICONV_COMPILES) 
CMake Error at cmake/FindIconv.cmake:130 (MESSAGE):
  Unable to determine iconv() signature
Call Stack (most recent call first):
  CMakeLists.txt:92 (find_package)

Thanks

**Comment by stayprivates** [comment]
Same with master as of today
