### ISSUE TITLE
GCC 6.2 build fails - Mac OS X 10.5.8 PPC

### ISSUE THREAD

**Issue by oboroc** [mistydemeo/tigerbrew#518]
I tried `brew install gcc6` and it got quite far, but failed as some point:

```
$ brew install gcc6
==> Installing dependencies for gcc6: gmp, mpfr, libmpc, isl014
==> Installing gcc6 dependency: gmp
==> Downloading https://ia902307.us.archive.org/31/items/tigerbrew/gmp-6.0.0a.le
######################################################################## 100.0%
==> Pouring gmp-6.0.0a.leopard_altivec.bottle.tar.gz
/usr/local/Cellar/gmp/6.0.0a: 15 files, 3.1M
==> Installing gcc6 dependency: mpfr
==> Downloading https://ia902307.us.archive.org/31/items/tigerbrew/mpfr-3.1.3.le
######################################################################## 100.0%
==> Pouring mpfr-3.1.3.leopard_altivec.bottle.tar.gz
/usr/local/Cellar/mpfr/3.1.3: 24 files, 3.5M
==> Installing gcc6 dependency: libmpc
==> Downloading https://ia902307.us.archive.org/31/items/tigerbrew/libmpc-1.0.3.
######################################################################## 100.0%
==> Pouring libmpc-1.0.3.leopard_altivec.bottle.tar.gz
/usr/local/Cellar/libmpc/1.0.3: 10 files, 352K
==> Installing gcc6 dependency: isl014
==> Downloading http://isl.gforge.inria.fr/isl-0.14.tar.bz2
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/isl014/0.14 --
==> make
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with isl in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/isl014/lib
    CPPFLAGS: -I/usr/local/opt/isl014/include

==> Summary
/usr/local/Cellar/isl014/0.14: 68 files, 3.0M, built in 7.9 minutes
==> Installing gcc6
==> Downloading https://ftpmirror.gnu.org/gcc/gcc-6.2.0/gcc-6.2.0.tar.bz2
######################################################################## 100.0%
==> Patching
patching file gcc/jit/Make-lang.in
==> ../configure --build=powerpc-apple-darwin9.8.0 --prefix=/usr/local/Cellar/gc
==> make bootstrap
Last 15 lines from /Users/oboroc/Library/Logs/Homebrew/gcc6/02.make:
checking sys/sdt.h in the target C library... yes
checking dl_iterate_phdr in target C library... unknown
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether to avoid linking multiple front-ends at once... no
Links are now set up to build a native compiler for powerpc-apple-darwin9.8.0.
checking Checking for isl_options_set_schedule_serialize_sccs... no
checking for exported symbols... yes
checking for library containing dlopen... none required
checking for -fPIC -shared... no
configure: error: 
   Building GCC with plugin support requires a host that supports
   -fPIC, -shared, -ldl and -rdynamic.
make[2]: *** [configure-stage1-gcc] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

READ THIS: https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting

```

**Comment by mistydemeo** [comment]
Could you run `brew gist-logs gcc`, and paste the link you get here?

**Comment by oboroc** [comment]
BTW: `brew install gcc5` worked.

Running `brew gist-logs gcc` gave me: `Error: No logs.`

Here is the output from `brew gist-logs gcc6`:

```
$ brew gist-logs gcc6
Error: uninitialized constant Homebrew::HOMEBREW_USER_AGENT
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/cmd/gist-logs.rb:95:in `make_request'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:113:in `post'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:72:in `create_gist'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:24:in `gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:140:in `gist_logs'
/usr/local/Library/brew.rb:143:in `send'
/usr/local/Library/brew.rb:143

```

**Comment by mistydemeo** [comment]
Oops, sorry about that! Should be fixed now, if you `brew update`.

**Comment by oboroc** [comment]
I did `brew update`, but it said "Already up-to-date."

`$ brew gist-logs gcc6`
https://gist.github.com/ac49fdda5154ce40ea65f8b36fb9bd0d

**Comment by oboroc** [comment]
@mistydemeo any idea why it fails? I checked on x86 Tiger Server and it also fails.

**Comment by g8kig** [comment]
@mistydemo. Still the same problem.

**Comment by jormundgand** [comment]
Same problem on 10.6 x86 :-(

**Comment by mistydemeo** [comment]
@jormundgand Can you confirm that the error you're seeing is the "Building GCC with plugin support requires a host that supports -fPIC, -shared, -ldl and -rdynamic." error?

**Comment by mistydemeo** [comment]
Fixed for 10.5! @jormundgand, if you can provide logs for your 10.6 build, I'll push another fix for that if necessary.

**Comment by nicklaslof** [comment]
This issue is back again with this commit two weeks ago: https://github.com/mistydemeo/tigerbrew/commit/999d7602272b84d8ba5d3f612930cc91d24b670e

it only checks for tiger and not leopard again. I changed it locally in my formula and got past the error.

**Comment by sevan** [comment]
You're referring to enabling plugin support?

**Comment by sevan** [comment]
Apologies, completely misread the line & assumed it was working on Tiger, then propagated the change to GCC 6 & 7 when it came to updating those formulas.
