### ISSUE TITLE
Bclm failed to build on 10.9.5

### ISSUE THREAD

**Issue by precabal** [mistydemeo/tigerbrew#712]
Hi, when trying to build [bclm](https://github.com/zackelia/bclm) with tigerbrew, I'm getting the error described in the following gist:

https://gist.github.com/precabal/027f4f112040b22e2430a1f9217a9ba0

I'd appreciate if you can take a look... (my `brew doctor` seems messed up).

**Comment by mistydemeo** [comment]
Looks like it's using a newer syntax Tigerbrew doesn't support yet. I'll see if I can backport support for it, or at least loosely patch it to fix it up.

**Comment by mistydemeo** [comment]
Fixed! It looks like the formula is installing a prebuilt x86_64 binary, so it'll only run on Intel Macs - but that should be fine for you on 10.9, assuming you have a 64-bit CPU.

**Comment by precabal** [comment]
Hi, thanks for addressing this. 
Unfortunately, I'm still getting the same error. I thought it might had to do with doing `brew update`, but when I run that, I get the following error:

```
Stashing your changes:
UU Formula/gmp.rb
Formula/gmp.rb: needs merge
Error: Failed to update tap: homebrew/core
Already up-to-date.
```

**Comment by precabal** [comment]
After doing a clean install of tigerbrew, I can confirm this works. Thanks!

**Comment by mistydemeo** [comment]
Great! Glad to hear it.
